### ISSUE TITLE
Add functions

### ISSUE THREAD

**Issue by normanrz** [cdglabs/Shadershop#7]
Great project! I love to prototype functions with this. 
How can I add other primitive functions like `min` and `max`. I'd love to submit a PR but am a bit confused where I need to put the changes in the code. So far I've spotted https://github.com/cdglabs/Shadershop/blob/gh-pages/src/model/model.coffee#L352-L366 but adding the functions there didn't seem to be enough.

**Comment by electronicwhisper** [comment]
I think adding min and max makes sense, though I think they should be "combiners" like add, multiply, and compose rather than primitive functions in the left hand column. To do this would require changing some code in multiple places because there are several "interpreters" that would need to know how to handle min and max (you could probably search the code for "compose" eg to find all these places).
